### ISSUE TITLE
建议 lemon开发团队在Releases中提供以本仓库源码+GitHub Actions方式构建出的dmg以供下载。

### ISSUE THREAD

**Issue by MoshiCoCo** [Tencent/lemon-cleaner#12]
没别的意思哈，仅仅是一条建议。

此条issues 只是一条建议，虽然很多人也有能力自己打包构建，但还是建议腾讯Lemon的开发团队使用GitHub Actions，提供一个公开的构建打包流程，然后以本仓库源码为基础构建出dmg发布到仓库Releases中。

非常感谢腾讯的开源！！！

**Comment by tanranran** [comment]
？？那你为啥不去官网下载

**Comment by MoshiCoCo** [comment]
> ？？那你为啥不去官网下载

此建议的目的就是让官方提供【一个透明构建流程和使用此流程构建出的产物】。

你问我为什么不去官网下载，因为官网下载的dmg不一定是基于这套开源代码构建的。 当然，我自己也有能力去下源码构建，所以本条issues仅是一个建议。

**Comment by iHTCboy** [comment]
现实，没必要，有能力看代码的朋友必然自己构建，甚至还会魔改....😜

**Comment by sbfkcel** [comment]
这个要同意，话说去官网下载的也不敢用。

**Comment by jusuoli** [comment]
这个建议挺好的，支持一下。
