### ISSUE TITLE
以化腾的名声，狗都不用

### ISSUE THREAD

**Issue by chacha20** [Tencent/lemon-cleaner#19]
以化腾的名声，狗都不用

**Comment by southcat** [comment]
你不用 狗也不用， 你==狗 ，没必要因为名声否定一个软件

**Comment by auula** [comment]
没有必要去喷一个软件，人家有开源的权利。

**Comment by wsafight** [comment]
感觉不错，不确定，再看看

**Comment by chacha20** [comment]
> 

名声就可以毁掉一个软件，你<=狗

**Comment by southcat** [comment]
> 名声就可以毁掉一个软件，你<=狗

人家把一个优秀的软件开源了，您呢？开源怎么当喷子吗🫡

**Comment by harofan** [comment]
喷子可真无脑

**Comment by Romic77** [comment]
为什么不用mac clean pro?

**Comment by chacha20** [comment]
ONCE A THIEF, ALWAYS A THIEF.

**Comment by southcat** [comment]
> ONCE A THIEF, ALWAYS A THIEF.

还搁这崩洋屁，怎么你洋爹的屁就这么香

**Comment by chacha20** [comment]
你化腾爹的屁更香是吧

**Comment by southcat** [comment]
> 你没读过小学？你化腾爹的屁更香，你不吠人化腾爹不给你骨头？

你化腾爷爷的屁不香，但是你化腾爷爷放的中国屁，不像你和你的洋爹只会崩洋屁

**Comment by chacha20** [comment]
噗，你只会放屁！

**Comment by ox01024** [comment]
狗都会提ISSUES了哈

**Comment by AAChartModel** [comment]
> 为什么不用mac clean pro?

你有空可以看看活动监视器里面的内容，流氓进程怎么都杀不死

**Comment by Gankyun** [comment]
哎，又一个二极管思维的人。

**Comment by xpilot2000** [comment]
哟，好热闹！

不过说来说去，柠檬没用过，以库克大叔的尿性，化腾爷爷很难在Mac上弹窗，鸿祎教父也没办法弹窗杀毒，艳红还在用小度录着人家叫床的声音，大环境如此，就别去单独指责化腾咋滴咋滴了。难得出来一下，为啥还要回去装这些国产软件呢？不过腾讯能专心做一个据说优秀的清理软件，也代表着要和过去旧事说拜拜了，这算是好事。

相信现在腾讯里头的00后员工都不知道这个梗：
- 为什么化腾深夜做了一个艰难的决定？
- 为什么腾讯软件任意装一个就会带进腾讯全家桶，顺便捎带金山全家桶？
- 为什么卸载了腾讯管家360管家电脑会巨卡？装回去就不卡了，可新装的系统不装这些乱七八糟的反而更快？

这是只有在Windows上才能这么闹，MacOS可是一直在安静看热闹的，楼主估计就是这个全家桶的受害者之一。桌面上看看3Q打架不更精彩吗？右下角弹点美女摇晃图不更能提神醒脑吗？哈哈

现在是2202年了，发展了这么多年的互联网公司，都会一点点把自己洗白的，再不洗白自己就被洗掉了，继续等等吧。都洗洗睡吧。

**Comment by shawn-yee** [comment]
腾讯在mac上几个软件都不错的
希望不要烂尾，持续跟新

**Comment by kapny** [comment]
跳梁小丑 污染开源环境

**Comment by yangliu-1995** [comment]
你不用 所以 你=狗

**Comment by zongkx** [comment]
厚礼蟹

**Comment by chacha20** [comment]
> 你不用 所以 你=狗

你用，所以你<狗

**Comment by xianyongjian080402** [comment]
别在开源社区这里说这些，有点素质。
