### ISSUE TITLE
大家都是内网来报道的吗？手动狗头

### ISSUE THREAD

**Issue by athenakia** [Tencent/lemon-cleaner#20]
😎

**Comment by RigoLigoRLC** [comment]
外网看到别人star的过来的，目前还没搞定编译。。。似乎文件有缺

**Comment by iHTCboy** [comment]
所以，怎么想到要开源了，是没有探索出商业化变现方案，还是不维护了？🤔

**Comment by AAChartModel** [comment]
@iHTCboy  我觉得直接像 cleanMyMac 一样做收费订阅就可以了, 便宜点, 应该还是有不少用户的.

**Comment by orangejx** [comment]
> 所以，怎么想到要开源了，是没有探索出商业化变现方案，还是不维护了？🤔

同感

**Comment by wxwldu** [comment]
> 

我这里修改了证书，本地就可以跑起来了

**Comment by Huweicai** [comment]
今天在 Trending 看到的

**Comment by Gankyun** [comment]
要收费的话市场上已经有一堆了，估计也不好卖，估计赚的钱都不够两个程序员工资多。

**Comment by boyeye** [comment]
要收费可以，前提是产品要有高完成度，别像个半成品似的。
