### ISSUE TITLE
M1 chip remove universal binary files cause .app damaged

### ISSUE THREAD

**Issue by Gunale0926** [Tencent/lemon-cleaner#23]
此功能应该去除，否则会导致删掉其他版本binary的app损坏

**Comment by dawnightillight** [comment]
请问是哪些app出现了损坏呢，可以提供下软件名称版本及mac系统版本我们看看

**Comment by CarterGunale** [comment]
> 请问是哪些app出现了损坏呢，可以提供下软件名称版本及mac系统版本我们看看

还有QQ也出现了问题，系统macOS 13.0 Developer Beta 5

**Comment by qiyuey** [comment]
13.0 Beta5，应该是清理到的全部都被损坏了

**Comment by soxft** [comment]
同遇到该问题, qq, telegram, neteaseMusic

**Comment by ae86jack** [comment]
几乎全军覆没。包括微信，obsidian, Docker，WPS，网易云音乐, alt-tab等等。大部分工作软件都要重装。再也不敢用lemon了。

**Comment by ae86jack** [comment]
系统版本是 13.0.1 (22A400)， 电脑是M1 Pro。

**Comment by dawnightillight** [comment]
官网最新版本v5.1.1已移除macOS13上的二进制清理功能，以避免误清除导致应用无法使用的问题。

**Comment by lzskyline** [comment]
同样是该功能的受害者，app还好说，rzsz永久性的出现乱码了，unicode部分控制字符不能正确执行，至今没研究出来解决方案。
别人sz输出**B0000000000000，我输出?*B0000000000000。难顶
