### ISSUE TITLE
你真的是腾讯吗？

### ISSUE THREAD

**Issue by ghost** [Tencent/lemon-cleaner#3]
腾讯开源？不敢相信

**Comment by CofinCup** [comment]
《论为什么有人不看开源历史连组织名都不肯点开就开始说不敢相信》

**Comment by chinsyo** [comment]
> 腾讯开源？不敢相信

开源社区需要的是包容和协作，不是傲慢和偏见。你这番回复除了狭隘和戾气并没有为社区带来别的作用。不论认可与否，腾讯无论是体量还是开源项目的数量都在中国科技企业里位列前茅了。
