### ISSUE TITLE
感谢开源，很好奇每年迭代最新的这些API都是通过哪些渠道找到的？

### ISSUE THREAD

**Issue by nanayashiki1215** [Tencent/lemon-cleaner#32]
看到了很多从没见过的底层API，很好奇每年苹果迭代最新的这些API都是通过哪些渠道找到的？我翻了苹果文档都没找到。

**Comment by Dywane** [comment]
看具体指的是哪一部分，部分API是通过逆向macOS底层实现的，底层API相对于上层API的变动也比较少（更偏向于C接口）；部分是比较少用的接口，如`OwlManageDaemon`中`IOService`相关接口；
