### ISSUE TITLE
用它卸载软件之后，Mac程序控制台还有这个软件 想删也删不掉。。。

### ISSUE THREAD

**Issue by telltao** [Tencent/lemon-cleaner#41]
<img width="216" alt="image" src="https://user-images.githubusercontent.com/31477407/192099744-686a25fd-6c5c-4ba7-87c9-88228ecf79ac.png">

**Comment by cntrump** [comment]
可以把图标直接拖到回收站

**Comment by telltao** [comment]
> 可以把图标拖到回收站

我试过，但是拖不进去，
1，我重新安装了一次它 发现无法安装到控制台 
2，我执行了anaconda软件安装到控制台的命令
3，我在程序里卸载掉，这样它才没有了

**Comment by Jerry23011** [comment]
下次按住command+option+control，点击“x”图标即可删除，如果好用这个issue就可以被关闭了

**Comment by telltao** [comment]
应该不是，我在柠檬控制台删除软件的时候，它并没有吧我启动台的软件图标删除掉，您说的这个问题， 用 command+option+control 这个软件上面是没有 “x”图标 的 类似这样，后来我重新安装软件又在应用程序那里移动到废纸篓，图标就没了
<img width="1273" alt="image" src="https://user-images.githubusercontent.com/31477407/209605438-ccd8b2c5-e47b-49dd-b140-337701e5ea57.png">

**Comment by telltao** [comment]
我先关掉这个issues吧，非常感谢谢楼上各位，向你们鞠躬，感谢。

**Comment by Jerry23011** [comment]
感谢回复，可能是`应用程序` 文件夹中的没删干净？
