### ISSUE TITLE
清理QQ微信缓存之后QQ微信打开软件提示损坏，无法使用

### ISSUE THREAD

**Issue by dlfld** [Tencent/lemon-cleaner#46]
清理QQ微信缓存之后QQ微信打开软件提示损坏，无法使用

**Comment by iwtkings** [comment]
升级到mac os 13系统之后，清理垃圾后，微信提示损坏，无法使用

**Comment by iwtkings** [comment]
<img width="338" alt="image" src="https://user-images.githubusercontent.com/8486299/198753387-e8e9e2e5-1138-468f-8967-b7481a6291ef.png">

**Comment by dawnightillight** [comment]
duplicated with
https://github.com/Tencent/lemon-cleaner/issues/40
