### ISSUE TITLE
操作系统语言是中文的时候，brew install tencent-lemon 能自动把应用名命名为『柠檬清理』而不是英文吗？每次都要找半天

### ISSUE THREAD

**Issue by usrtax** [Tencent/lemon-cleaner#47]
操作系统语言是中文的时候，brew install tencent-lemon 能自动把应用名命名为『柠檬清理』而不是英文吗？每次都要找半天

**Comment by betterlmy** [comment]
这。。好像没有必要吧 而且用命令行里有中文难以理解

**Comment by usrtax** [comment]
<img width="776"  src="https://user-images.githubusercontent.com/110233389/216498346-5779b82d-ba3b-4cd1-ba66-c334960a57f7.png">
@betterlmy 看截图 brew install --cask foxitreader ，安装后的软件名是 福昕阅读器
<img width="446" alt="image" src="https://user-images.githubusercontent.com/110233389/216498465-7feeec70-9174-40c1-923c-0fc1020a9e8f.png">

**Comment by jyxjjj** [comment]
那是因为人家只支持中文吧，然后brew包也不是官方提交的吧
```
url "https://pm.myapp.com/invc/xfspeed/qqpcmgr/module_update/Lemon_#{version}.dmg",
```
```
https://cdn78.foxitsoftware.com/pub/foxit/phantomPDF/desktop/mac/#{version}/FoxitPDFReader#{version.no_dots}.L10N.Setup.pkg
```

brew 只有一个下载的功能，不管软件叫什么名称，".app"这个实际上只是一个文件夹，而且你看到L10N这个说明人家本来就只写了当个语言，而且还是pkg不是dmg，镜像存储的更加是原文件夹名称了。

再说brew的问题能不能提到brew去？
你foxit的brew作者是 @getong
lemon的brew作者是 @zuisong
是不是有人不会用GitHub啊

**Comment by zuisong** [comment]
关于名字的问题， 直接下载官网的dmg安装包手动安装， 安装出来也是叫  `Tencent Lemon` 

hombrew 倒是有能力在安装的时候改 软件名称为 `柠檬清理` ，只是我感觉没有必要， 尊重官网官网下载的包名称

**Comment by getong** [comment]
foxit跟我没有关系，我纯粹看到homecask上的foxit很久没有更新了，帮忙更新了一下url地址而已。
