### ISSUE TITLE
文件夹有拼写错误LemonClener

### ISSUE THREAD

**Issue by GendSmith** [Tencent/lemon-cleaner#5]
LemonClener -> LemonCleaner

**Comment by CitizenChaos** [comment]
确实

**Comment by CitizenChaos** [comment]
![GF12NUMJR3PCIA8SIPMKJ0A](https://user-images.githubusercontent.com/48626014/181181407-9d3d9102-5a4f-4007-aa5f-4cee9d5471f3.jpg)

**Comment by SeeHaze** [comment]
![8~R)Z`{P591TBL@K@P0V1@V](https://user-images.githubusercontent.com/28894456/181181679-14a6c4a1-a80e-4217-a19d-1212122e28b7.jpg)

**Comment by dawnightillight** [comment]
感谢反馈
