### ISSUE TITLE
更新仓库代码

### ISSUE THREAD

**Issue by Jerry23011** [Tencent/lemon-cleaner#51]
已经2023了，现在GitHub上的还是半年前的，请问可以将最新的代码同步到仓库方便自行编译最新版本吗？

**Comment by yiguanxianyu** [comment]
我猜这个项目已经弃了）

**Comment by Jerry23011** [comment]
> 我猜这个项目已经弃了）

没有啊，还有在更新，只是GitHub上没同步源码而已

**Comment by dawnightillight** [comment]
感谢关注，GitHub上的代码是和官网最新版本同步更新的。

**Comment by Jerry23011** [comment]
非常感谢！😄🙏🏻

**Comment by errNo7** [comment]
> 感谢关注，GitHub上的代码是和官网最新版本同步更新的。

规则不是最新的

**Comment by dawnightillight** [comment]
> > 感谢关注，GitHub上的代码是和官网最新版本同步更新的。
> 
> 规则不是最新的

规则作为运营策略的一部分，不随代码一同更新。
