### ISSUE TITLE
cpu温度显示不正常

### ISSUE THREAD

**Issue by woshidaifu** [Tencent/lemon-cleaner#61]
mac pro M2芯片，cpu温度始终显示6度。

**Comment by Kreveyn** [comment]
我也是 你也Sonoma吗？

**Comment by jyxjjj** [comment]
5.1.2 似乎修复了

**Comment by yuanyuan100** [comment]
我是lemon的技术支持人员，我们的客服QQ:3804589419。如果有类似问题欢迎联系我们，获取最新的体验包尝试一下。
